#ifndef __DIRECTION_MODEL_4CH_WEIGHTS_H
#define __DIRECTION_MODEL_4CH_WEIGHTS_H

/* Auto-generated by train_direction_24d.py.
 * Input protocol: 24 integer features carried by DIRCSV.
 * Model input: feat0..feat13 spatial narrow-band features.
 * feat14..feat23 are protocol padding and have zero weights.
 * Labels: LEFT=0 and RIGHT=1 internally; firmware DIRCSV uses 2/3.
 * Model: 14D spatial narrow-band shrinkage LDA (solver=lsqr, shrinkage=auto).
 * Positive decision value means RIGHT.
 * Legacy svm variable names are retained so V5F firmware stays unchanged.
 */

#define DIR4CH_INPUT_DIM 24
#define DIR4CH_WEIGHTS_TRAINED 1

static const float dir4ch_mean[24] = {
    1.064451042e+04f, 1.141510938e+04f, 1.156231771e+04f, 1.200277083e+04f, 1.139446875e+04f, 1.062188021e+04f,
    1.006470833e+04f, 1.008553646e+04f, 1.144350521e+04f, 1.462803125e+04f, 1.133072917e+04f, 9.864692708e+03f,
    1.176973438e+04f, 1.161690104e+04f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_scale[24] = {
    1.515426335e+04f, 1.518671187e+04f, 1.416114447e+04f, 1.084155427e+04f, 1.027979278e+04f, 1.058075589e+04f,
    1.019926938e+04f, 1.398169930e+04f, 1.360991947e+04f, 1.330412022e+04f, 1.102567417e+04f, 9.727732632e+03f,
    9.449681960e+03f, 9.245614418e+03f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
    1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
};

static const float dir4ch_svm_weight[24] = {
    -1.684348125e-01f, -1.399491572e-01f, 1.570742471e-01f, 1.110365959e-01f, 7.395991924e-02f, -2.840720707e-02f,
    -2.235957905e-01f, 3.366507119e-01f, 1.940183548e-01f, 9.268047908e-02f, 9.979621966e-02f, -7.259082357e-02f,
    -7.994404580e-02f, -1.315580598e-01f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_svm_bias = 0.000000000e+00f;

#endif /* __DIRECTION_MODEL_4CH_WEIGHTS_H */
