#ifndef __DIRECTION_MODEL_4CH_WEIGHTS_H
#define __DIRECTION_MODEL_4CH_WEIGHTS_H

/* Auto-generated by train_direction_24d.py.
 * Input protocol: 24 integer features carried by DIRCSV.
 * Model input: feat0..feat13 spatial narrow-band features.
 * feat14..feat23 are protocol padding and have zero weights.
 * Labels: LEFT=0 and RIGHT=1 internally; firmware DIRCSV uses 2/3.
 * Model: 14D spatial narrow-band shrinkage LDA (solver=lsqr, shrinkage=auto).
 * Positive decision value means RIGHT.
 * Legacy svm variable names are retained so V5F firmware stays unchanged.
 */

#define DIR4CH_INPUT_DIM 24
#define DIR4CH_WEIGHTS_TRAINED 1

static const float dir4ch_mean[24] = {
    -2.794812500e+03f, -1.521375000e+03f, 1.111656250e+03f, 3.306718750e+02f, 7.534375000e+01f, 1.716828125e+03f,
    2.285000000e+02f, -4.980609375e+03f, -5.546250000e+02f, -2.936093750e+03f, -1.996875000e+03f, 7.792187500e+01f,
    2.818125000e+02f, -4.823437500e+02f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_scale[24] = {
    1.403270930e+04f, 1.275171670e+04f, 1.333041627e+04f, 1.014766862e+04f, 9.518705291e+03f, 8.604651942e+03f,
    7.599821207e+03f, 1.207280863e+04f, 1.226530288e+04f, 1.203047854e+04f, 9.454416261e+03f, 1.031692066e+04f,
    1.086111464e+04f, 9.425887243e+03f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
    1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
};

static const float dir4ch_svm_weight[24] = {
    -4.796712598e-02f, -8.414065479e-02f, -1.790341680e-01f, 1.105186587e-01f, -2.672819076e-01f, 4.758063307e-02f,
    1.388446612e-01f, -2.880327140e-01f, 5.308894560e-01f, 8.365051909e-02f, 1.382926732e-02f, 1.092157923e-01f,
    9.500818059e-02f, -1.440716413e-01f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_svm_bias = 0.000000000e+00f;

#endif /* __DIRECTION_MODEL_4CH_WEIGHTS_H */
