#ifndef __DIRECTION_MODEL_4CH_WEIGHTS_H
#define __DIRECTION_MODEL_4CH_WEIGHTS_H

/* Auto-generated by train_direction_24d.py.
 * Input protocol: 24 integer features carried by DIRCSV.
 * Model input: feat0..feat13 spatial narrow-band features.
 * feat14..feat23 are protocol padding and have zero weights.
 * Labels: LEFT=0 and RIGHT=1 internally; firmware DIRCSV uses 2/3.
 * Model: 14D spatial narrow-band shrinkage LDA (solver=lsqr, shrinkage=auto).
 * Positive decision value means RIGHT.
 * Legacy svm variable names are retained so V5F firmware stays unchanged.
 */

#define DIR4CH_INPUT_DIM 24
#define DIR4CH_WEIGHTS_TRAINED 1

static float dir4ch_mean[24] = {
    6.076888021e+03f, 7.390804688e+03f, 6.414773438e+03f, 9.411216146e+03f, 9.456330729e+03f, 8.067552083e+03f,
    7.483419271e+03f, 6.935023438e+03f, 9.891752604e+03f, 1.144559896e+04f, 9.486713542e+03f, 9.176367188e+03f,
    1.085832292e+04f, 1.101967708e+04f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static float dir4ch_scale[24] = {
    1.584722674e+04f, 1.501639106e+04f, 1.470766820e+04f, 1.138430877e+04f, 1.076294616e+04f, 1.044152533e+04f,
    9.765927798e+03f, 1.295283500e+04f, 1.281585908e+04f, 1.317921194e+04f, 1.020919375e+04f, 1.013366135e+04f,
    9.732021952e+03f, 8.656396420e+03f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
    1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
};

static float dir4ch_svm_weight[24] = {
    -2.915672369e-01f, 4.869705855e-02f, 1.871935282e-01f, -5.582831689e-02f, -2.362149731e-02f, 7.460852367e-02f,
    -5.813517494e-02f, 1.726426504e-01f, -1.134822819e-01f, 8.891383411e-03f, -1.885563958e-01f, -1.360347802e-01f,
    1.072917120e-02f, -8.164467209e-02f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static float dir4ch_svm_bias = 0.000000000e+00f;

#endif /* __DIRECTION_MODEL_4CH_WEIGHTS_H */
