#ifndef __DIRECTION_MODEL_4CH_WEIGHTS_H
#define __DIRECTION_MODEL_4CH_WEIGHTS_H

/* Auto-generated by train_direction_24d.py.
 * Input protocol: 24 integer features carried by DIRCSV.
 * Model input: feat0..feat13 spatial narrow-band features.
 * feat14..feat23 are protocol padding and have zero weights.
 * Labels: LEFT=0 and RIGHT=1 internally; firmware DIRCSV uses 2/3.
 * Model: 14D spatial narrow-band shrinkage LDA (solver=lsqr, shrinkage=auto).
 * Positive decision value means RIGHT.
 * Legacy svm variable names are retained so V5F firmware stays unchanged.
 */

#define DIR4CH_INPUT_DIM 24
#define DIR4CH_WEIGHTS_TRAINED 1

static const float dir4ch_mean[24] = {
    -1.984620968e+04f, -1.485153226e+04f, -1.194600000e+04f, -1.137041935e+04f, -4.000258065e+03f, -4.407935484e+03f,
    -4.245935484e+03f, -1.726158065e+04f, -1.007979032e+04f, -5.530596774e+03f, -5.310370968e+03f, 3.026870968e+03f,
    3.339258065e+03f, 3.000145161e+03f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_scale[24] = {
    1.566424164e+04f, 1.649495737e+04f, 1.563710430e+04f, 1.496418150e+04f, 1.197140700e+04f, 1.028264740e+04f,
    1.163471851e+04f, 1.585953537e+04f, 1.669585851e+04f, 1.836610577e+04f, 1.575141948e+04f, 1.350972172e+04f,
    1.175506763e+04f, 1.388002260e+04f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
    1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
};

static const float dir4ch_svm_weight[24] = {
    5.536672212e-01f, 3.761212730e-01f, -6.914128269e-02f, 7.938990569e-01f, 4.506238186e-01f, 1.901535936e-01f,
    2.087159421e-01f, -4.424560938e-01f, -3.414763578e-01f, -3.144113847e-01f, 2.818452368e-01f, -3.628430662e-01f,
    -1.225469194e-01f, -2.090753438e-01f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_svm_bias = 0.000000000e+00f;

#endif /* __DIRECTION_MODEL_4CH_WEIGHTS_H */
