#ifndef __DIRECTION_MODEL_4CH_WEIGHTS_H
#define __DIRECTION_MODEL_4CH_WEIGHTS_H

/* Auto-generated by train_direction_24d.py.
 * Input protocol: 24 integer features carried by DIRCSV.
 * Model input: feat0..feat13 spatial narrow-band features.
 * feat14..feat23 are protocol padding and have zero weights.
 * Labels: LEFT=0 and RIGHT=1 internally; firmware DIRCSV uses 2/3.
 * Model: 14D spatial narrow-band shrinkage LDA (solver=lsqr, shrinkage=auto).
 * Positive decision value means RIGHT.
 * Legacy svm variable names are retained so V5F firmware stays unchanged.
 */

#define DIR4CH_INPUT_DIM 24
#define DIR4CH_WEIGHTS_TRAINED 1

static const float dir4ch_mean[24] = {
    -1.103263125e+04f, -1.249821563e+04f, -1.175282812e+04f, -9.243996875e+03f, -9.162862500e+03f, -8.566128125e+03f,
    -8.261303125e+03f, -4.432343750e+03f, -2.052843750e+03f, -3.120418750e+03f, -4.440809375e+03f, -5.290518750e+03f,
    -5.496943750e+03f, -6.115734375e+03f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_scale[24] = {
    1.475468859e+04f, 1.396843558e+04f, 1.295230292e+04f, 1.022849562e+04f, 1.059251527e+04f, 9.815350270e+03f,
    8.391137653e+03f, 1.268795624e+04f, 1.313537479e+04f, 1.184630633e+04f, 9.407448732e+03f, 9.373051228e+03f,
    8.775625140e+03f, 9.305132297e+03f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
    1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
};

static const float dir4ch_svm_weight[24] = {
    5.015932593e-02f, 3.434297217e-02f, 2.271833139e-01f, 2.331541022e-03f, -5.218833127e-02f, -1.153322346e-01f,
    1.534805597e-01f, -1.998602426e-01f, -1.084136522e-01f, -9.117173669e-02f, -8.486392772e-02f, -2.082791647e-01f,
    -1.413202937e-01f, 3.949291235e-02f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_svm_bias = 0.000000000e+00f;

#endif /* __DIRECTION_MODEL_4CH_WEIGHTS_H */
