#ifndef __DIRECTION_MODEL_4CH_WEIGHTS_H
#define __DIRECTION_MODEL_4CH_WEIGHTS_H

/* Auto-generated by train_direction_24d.py.
 * Input protocol: 24 integer features carried by DIRCSV.
 * Model input: feat0..feat13 spatial narrow-band features.
 * feat14..feat23 are protocol padding and have zero weights.
 * Labels: LEFT=0 and RIGHT=1 internally; firmware DIRCSV uses 2/3.
 * Model: 14D spatial narrow-band shrinkage LDA (solver=lsqr, shrinkage=auto).
 * Positive decision value means RIGHT.
 * Legacy svm variable names are retained so V5F firmware stays unchanged.
 */

#define DIR4CH_INPUT_DIM 24
#define DIR4CH_WEIGHTS_TRAINED 1

static const float dir4ch_mean[24] = {
    -1.718181569e+04f, -1.568331765e+04f, -1.546129020e+04f, -1.832592941e+04f, -1.882672157e+04f, -1.857230588e+04f,
    -1.885926667e+04f, -8.723356863e+03f, -7.203917647e+03f, -6.826941176e+03f, -9.422301961e+03f, -9.643062745e+03f,
    -9.608376471e+03f, -9.463141176e+03f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_scale[24] = {
    9.335074784e+03f, 8.816715368e+03f, 9.533619365e+03f, 5.611416970e+03f, 4.295000418e+03f, 4.294096952e+03f,
    3.356326950e+03f, 1.241709927e+04f, 1.159897437e+04f, 1.318246159e+04f, 7.702575716e+03f, 5.682229797e+03f,
    5.591562640e+03f, 4.292124204e+03f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
    1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f, 1.000000000e+00f,
};

static const float dir4ch_svm_weight[24] = {
    2.297827348e-01f, 5.497864519e-02f, -2.608419462e-01f, -4.174477005e-01f, -5.716300198e-02f, -2.679205200e-01f,
    -2.261875892e-01f, -3.442016759e-01f, 3.356653466e-02f, 6.202392228e-02f, -8.762071105e-02f, -1.851587241e-01f,
    4.777731540e-02f, 3.192180260e-01f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
    0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f, 0.000000000e+00f,
};

static const float dir4ch_svm_bias = 1.019477297e-03f;

#endif /* __DIRECTION_MODEL_4CH_WEIGHTS_H */
